In [4]:
import pandas
import numpy

Read Liquor Data

In [5]:
liquor = pandas.read_csv('C:\\Users\\shiva\\Desktop\\DPA\\Iowa_Liquor_Sales.csv')

Create a subset of only Store Data 
i.e(
Store Number,
Address,
City,
Zip Code,
Store Location,
County Number,
County) 
and then drop any duplicate records 

In [7]:
df = liquor[liquor.columns[2:10]] 
#df2 = df.dropna()
df2 = df.drop(['Store Name'],axis = 1)
df2 = df.drop(['County Number'],axis = 1)
df2 = pandas.DataFrame(df2.drop_duplicates())

In [12]:
df2 = df2.drop(['County Number'],axis = 1)

In [13]:
df2.head()

Store Number                     Address            City Zip Code  \
0          2626         4100 University Ave      Des Moines    50311   
1          2501              640 Lincolnway            Ames    50010   
2          2508   1843 Johnson Avenue, N.W.    Cedar Rapids    52405   
3          5314  3134 Manawa Center Dr. # 9  Council Bluffs    51501   
4          2663                8701 Douglas       Urbandale    50322   

                 Store Location      County  
0  POINT (-93.673222 41.600361)        POLK  
1  POINT (-93.619455 42.022848)       STORY  
2   POINT (-91.697941 41.97447)        LINN  
3  POINT (-95.847514 41.228712)  POTTAWATTA  
4  POINT (-93.739105 41.629364)        POLK

Check there are no store number missing in the subset created 

In [5]:
len(liquor)

17926603

In [488]:
len(set(liquor['Store Number'])) 
#- set(df2['Store Number'])

2320

In [20]:
df2['Store Number'].value_counts(ascending=False)

5124    8
5102    8
4942    8
3456    8
4725    8
4091    8
2669    8
5167    8
4924    8
4969    8
3822    8
4640    8
4853    8
5051    8
5205    8
5070    8
4319    8
5176    8
2523    8
5140    8
2578    8
2515    8
5187    7
4457    7
2627    7
5105    7
4559    7
2655    7
4588    7
5091    7
       ..
5723    1
5715    1
5687    1
5595    1
5771    1
3492    1
5535    1
3480    1
5451    1
3172    1
5139    1
5759    1
5775    1
5835    1
9913    1
9929    1
5831    1
9925    1
5827    1
5823    1
5819    1
5811    1
5779    1
5803    1
5799    1
5795    1
5791    1
5787    1
5783    1
4080    1
Name: Store Number, Length: 2173, dtype: int64

The spelling and case corrections are done in R. Thus storing the dataframe as csv for further cleaning in R

In [37]:
df2.to_csv('C:\\Users\\shiva\\Desktop\\DPA\\Master_Data_Stores.csv')

In R, Spellings, special characters, and cases of County, City, Address were normalized and again the duplicate rows  encountered were dropped. Load the csv file with changes done in R

In [338]:
Store = pandas.read_csv('C:\\Users\\shiva\\Desktop\\DPA\\Store_Cleaned.csv')
Store = Store.drop(['Unnamed: 0'],axis = 1)

In [342]:
Store.head()

Store.Number  Zip.Code                Store.Location  County.Number  \
0          2626   50311.0  POINT (-93.673222 41.600361)           77.0   
1          2501   50010.0  POINT (-93.619455 42.022848)           85.0   
2          2508   52405.0   POINT (-91.697941 41.97447)           57.0   
3          5314   51501.0  POINT (-95.847514 41.228712)           78.0   
4          2663   50322.0  POINT (-93.739105 41.629364)           77.0   

             Address Cleaned    City Cleaned County Cleaned  
0        4100 University Ave      Des Moines           Polk  
1             640 Lincolnway            Ames          Story  
2     1843 Johnson Avenue Nw    Cedar Rapids           Linn  
3  3134 Manawa Center Dr # 9  Council Bluffs     Pottawatta  
4               8701 Douglas       Urbandale           Polk

In [339]:
len(Store) #We can see the row count has significantly decreaesd

2710

In [351]:
set(df2['Store Number']) - set(Store['Store.Number']) # Making sure no Store number was missed

set()

In [340]:
Store.isna().any()

Store.Number       False
Zip.Code            True
Store.Location      True
County.Number       True
Address Cleaned     True
City Cleaned        True
County Cleaned      True
dtype: bool

Drop the rows which do not have any information about Zip.Code, Store.Location, County.Number,Address CleanedCity Cleaned and    County Cleaned i.e all columns except Store.Number are null

In [437]:
Store_Cleaned

Store.Number  Zip.Code                         Store.Location  \
0             2626   50311.0           POINT (-93.673222 41.600361)   
1             2501   50010.0           POINT (-93.619455 42.022848)   
2             2508   52405.0            POINT (-91.697941 41.97447)   
3             5314   51501.0           POINT (-95.847514 41.228712)   
4             2663   50322.0           POINT (-93.739105 41.629364)   
5             2527   50315.0           POINT (-93.602372 41.526289)   
6             5187   50010.0           POINT (-93.611773 42.026938)   
7             4134   50225.0           POINT (-93.269702 41.386718)   
8             2561   50321.0   POINT (-93.64494300000001 41.542748)   
9             4638   52804.0         POINT (-90.6097959 41.5675513)   
10            2562   50501.0   POINT (-94.15824700000002 42.504742)   
11            2233   51360.0           POINT (-95.126786 43.416433)   
12            3679   52159.0           POINT (-91.390767 43.055133)   
13            2524   52001.0  POINT (-90.72213219999999 42.4907476)   
14            2633   50320.0           POINT (-93.596754 41.554101)   
15            3841   52001.0           POINT (-90.665439 42.495308)   
16            4165   50023.0           POINT (-93.581093 41.731416)   
17            4137   50263.0            POINT (-93.86786 41.614033)   
18            4129   50010.0           POINT (-93.618911 42.022854)   
19            2500   50010.0         POINT (-93.6999877 42.0219973)   
21            2538   50702.0           POINT (-92.327917 42.459938)   
22            2566   50138.0         POINT (-93.1094608 41.3250653)   
23            4051   52060.0           POINT (-90.680623 42.067391)   
25            2602   50595.0           POINT (-93.825486 42.469466)   
26            4153   50707.0           POINT (-92.287834 42.475631)   
27            4487   52402.0           POINT (-91.662119 42.010447)   
28            4767   50023.0  POINT (-93.600659 41.687793000000006)   
29            2190   50314.0            POINT (-93.619787 41.60566)   
30            5144   50021.0              POINT (-93.581273 41.691)   
31            5067   50588.0           POINT (-95.200761 42.651369)   
...            ...       ...                                    ...   
2680          5297   50595.0           POINT (-93.815845 42.459531)   
2681          5279   50010.0            POINT (-93.618576 42.05119)   
2682          5291   51510.0   POINT (-95.92895200000001 41.285058)   
2683          5287   50525.0   POINT (-93.73592500000001 42.731643)   
2684          5294   50703.0           POINT (-92.314939 42.495308)   
2685          5302   50421.0            POINT (-93.616821 42.84535)   
2686          5283   50401.0   POINT (-93.221539 43.14833900000001)   
2687          5280   50401.0           POINT (-93.201072 43.133204)   
2688          5304   50583.0           POINT (-94.857286 42.421722)   
2689          5269   52202.0              POINT (-91.618537 42.148)   
2690          5300   52501.0           POINT (-92.418553 41.009435)   
2691          5290   50206.0           POINT (-93.049443 41.699578)   
2692          5301   52501.0           POINT (-92.409169 41.051858)   
2693          9910   50211.0           POINT (-93.712272 41.436457)   
2694          9922   52801.0           POINT (-90.570318 41.521305)   
2695          9919   50325.0            POINT (-93.719833 41.60039)   
2696          9913   50061.0           POINT (-93.762456 41.483192)   
2697          9928   52404.0           POINT (-91.687168 41.965789)   
2698          9929   52240.0           POINT (-91.452639 41.672544)   
2699          9930   50667.0           POINT (-92.219773 42.466651)   
2700          9912   50111.0           POINT (-93.774496 41.657621)   
2701          5595   50009.0            POINT (-93.464905 41.64404)   
2702          9925   50310.0   POINT (-93.67743500000002 41.628472)   
2703          9931   51530.0           POINT (-95.479709 41.770879)   
2704          9932   52002.0  

In [377]:
Store[(Store['Store.Number'] == 2686) | (Store['Store.Number'] == 5320)]

Store.Number  Zip.Code Store.Location  County.Number Address Cleaned  \
1223          5320       NaN            NaN            NaN             NaN   
2562          2686       NaN            NaN            NaN             NaN   

     City Cleaned County Cleaned  
1223          NaN            NaN  
2562          NaN            NaN

Above you can see Store Number '2686' and '5320' provided no information regarding the Store and hence were dropped from data set

In [378]:
Store_Cleaned[Store_Cleaned['Store.Location'].isna()]

Store.Number  Zip.Code Store.Location  County.Number  \
9             4638   52804.0            NaN           82.0   
13            2524   52001.0            NaN           31.0   
19            2500   50010.0            NaN           85.0   
22            2566   50138.0            NaN           63.0   
34            2625   52804.0            NaN           82.0   
40            2539   50126.0            NaN           42.0   
44            2560   52302.0            NaN           57.0   
48            5286   52240.0            NaN           52.0   
52            4246   51601.0            NaN           73.0   
72            5104   51331.0            NaN           30.0   
74            4136   50111.0            NaN           77.0   
75            2596   52501.0            NaN           90.0   
89            2620   50311.0            NaN           77.0   
97            3868   52302.0            NaN           57.0   
111           2643   50701.0            NaN            7.0   
120           2549   50125.0            NaN           91.0   
123           2535   50265.0            NaN           77.0   
124           4222   50707.0            NaN            7.0   
127           3629   51503.0            NaN           78.0   
145           2502   50021.0            NaN           77.0   
148           5057   50317.0            NaN           77.0   
150           2528   50315.0            NaN           77.0   
163           4176   52405.0            NaN           57.0   
185           5025   52403.0            NaN           57.0   
211           3584   50662.0            NaN           33.0   
219           4334   52001.0            NaN           31.0   
251           2445   51560.0            NaN           78.0   
256           3417   52301.0            NaN           48.0   
266           3912   52405.0            NaN           57.0   
269           4254   50536.0            NaN           74.0   
...            ...       ...            ...            ...   
2096          2161   52144.0            NaN           96.0   
2108          5088   51238.0            NaN           84.0   
2117          4169   50317.0            NaN            NaN   
2146          3651   50125.0            NaN            NaN   
2150          3772   50314.0            NaN            NaN   
2164          5257   52501.0            NaN            NaN   
2172          5249   52803.0            NaN            NaN   
2183          5268   52206.0            NaN            NaN   
2194          5284   52211.0            NaN            NaN   
2200          5286   52240.0            NaN            NaN   
2203          5288   50501.0            NaN            NaN   
2207          5200   52328.0            NaN            NaN   
2209          5637   52001.0            NaN           31.0   
2222          5636   52402.0            NaN           57.0   
2226          5650   52361.0            NaN           48.0   
2236          5698   50111.0            NaN           77.0   
2240          2679   50009.0            NaN           77.0   
2247          5709   50014.0            NaN           85.0   
2305          5664   50317.0            NaN           77.0   
2307          2681   52556.0            NaN           51.0   
2314          9042   51301.0            NaN           21.0   
2323          2238   50009.0            NaN           77.0   
2328          5782   50322.0            NaN           77.0   
2361          5757   52531.0            NaN           68.0   
2367          5801   52213.0            NaN           57.0   
2371          5814   52002.0            NaN           31.0   
2391          5273   50219.0            NaN            NaN   
2428          5807   52638.0            NaN           29.0   
2588          5618   52253.0            NaN           57.0   
2594          5774   52057.0            NaN           28.0   

                       Address Cleaned     City Cleaned County Cleaned  
9                       4607 N Pine St        Davenport          Scott  
13             

We will now fill the missing Store Locations from the address, City, County and Zipcode information available

In [390]:
Store_Cleaned['add']= Store_Cleaned['Address Cleaned'] + " "+ Store_Cleaned['City Cleaned'] + " "+Store_Cleaned['County Cleaned']+ " "+ Store_Cleaned['Zip.Code'].astype(str)


C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [383]:
import googlemaps # function to get latitude and longitude 

def get_location(address):
    gmap_key = googlemaps.Client(key='AIzaSyD7yd0T_JLTzzLAbUEoIpREBXFMRtlq26M')
    result = gmap_key.geocode(address)
    try:
        location = "POINT (" + str(result[0]["geometry"]["location"]["lng"]) +" " + str(result[0]["geometry"]["location"]["lat"]) + ")"
    except:
        location = None
    return location

#Store_Cleaned['new_loc']=Store_Cleaned[Store_Cleaned['Store.Location'].isna() ].apply(lambda x: get_location(x.add), axis=1)

for i in range(len(Store_Cleaned)): # code for inserting latitude and longitude information in the dataset
    if pandas.isna(Store_Cleaned.iloc[i,2]):
        Store_Cleaned.iloc[i,2] = get_location(Store_Cleaned.iloc[i,7])



In [396]:
Store_Cleaned.isna().any()

Store.Number       False
Zip.Code            True
Store.Location     False
County.Number       True
Address Cleaned     True
City Cleaned       False
County Cleaned      True
add                 True
dtype: bool

We now get missing County from longitude and latitute

In [449]:
def latlon(point): # Function to get latitude and longitude from store location

    c = point.split("(")
    c = c[1].split(" ")
    lon = c[0]
    lat = c[1].split(")")[0]
    return lat,lon

from urllib.request import urlopen 
import json

def getplace(lat, lon): # function to get street,city,county and zipcode from latitude and longitude
    key = "AIzaSyD7yd0T_JLTzzLAbUEoIpREBXFMRtlq26M"
    url = "https://maps.googleapis.com/maps/api/geocode/json?"
    url += "latlng=%s,%s&sensor=false&key=%s" % (lat, lon, key)
    v = urlopen(url).read()
    j = json.loads(v)
    components = j['results'][0]['address_components']
    try:
        for c in components:
            if "locality" in c['types']:
                city = c['long_name']
            if "administrative_area_level_2" in c['types']:
                 county= c['long_name']
                 county = county.split(' ')
                 county = county[0]
            if "establishment" in c['types']:
                 street = c['long_name']
            if "postal_code" in c['types']:
                 zipcode = c['long_name']
        place = (street,city,county,zipcode)             
    except:
        place = None
    return place



In [450]:
# inserting street,city,county and zipcode information in dataset 
for i in range(len(Store_Cleaned)):
    lat, lon = latlon(Store_Cleaned.iloc[i,2])
    if pandas.isna(Store_Cleaned.iloc[i,1]) | pandas.isna(Store_Cleaned.iloc[i,4]) |  pandas.isna(Store_Cleaned.iloc[i,5]) | pandas.isna(Store_Cleaned.iloc[i,6]):
        lat, lon = latlon(Store_Cleaned.iloc[i,2])
        place = getplace(lat,lon)
    if pandas.notna(place):
        if pandas.isna(Store_Cleaned.iloc[i,1]):
            Store_Cleaned.iloc[i,1] = place[3]
        if pandas.isna(Store_Cleaned.iloc[i,4]):
            Store_Cleaned.iloc[i,4] = place[0]
        if pandas.isna(Store_Cleaned.iloc[i,5]):
            Store_Cleaned.iloc[i,5] = place[1]
        if pandas.isna(Store_Cleaned.iloc[i,6]):
            Store_Cleaned.iloc[i,6] = place[2]
    
    

In [473]:
# Making County names uniform
Store_Cleaned['County Cleaned']=Store_Cleaned['County Cleaned'].replace('Black$','Black Hawk',regex = True)
Store_Cleaned['County Cleaned']=Store_Cleaned['County Cleaned'].replace('Pottawattamiemie$','Pottawattamie',regex = True)
Store_Cleaned['County Cleaned']=Store_Cleaned['County Cleaned'].replace('Buena$','Buena Vista',regex = True)
Store_Cleaned['County Cleaned']=Store_Cleaned['County Cleaned'].replace('Cerro$','Cerro Gordo',regex = True)

In [501]:
Store_Cleaned['Store.Number'].value_counts()

4777    3
5268    3
4866    2
5774    2
5304    2
5801    2
5249    2
4416    2
5255    2
5257    2
3742    2
5259    2
5271    2
5267    2
5237    2
5273    2
5285    2
5287    2
5762    2
4779    2
4395    2
5350    2
5241    2
5298    2
3822    2
9911    2
3805    2
4320    2
5852    2
4944    2
       ..
4715    1
2666    1
4713    1
2664    1
2662    1
4737    1
4709    1
2660    1
4707    1
2658    1
4705    1
4703    1
2670    1
4719    1
2672    1
4721    1
2674    1
4723    1
2676    1
4725    1
2678    1
4727    1
2680    1
4729    1
4731    1
2684    1
4733    1
4735    1
2688    1
4098    1
Name: Store.Number, Length: 2318, dtype: int64

In [504]:
Store_Cleaned[Store_Cleaned['Store.Number'] == 3822]

Store.Number  Zip.Code                Store.Location  \
1466          3822   52338.0  POINT (-91.646067 41.847398)   
1734          3822   52338.0  POINT (-91.646067 41.847398)   

           Address Cleaned City Cleaned County Cleaned  
1466  1205 Curtis Br Rd Ne   Shueyville        Johnson  
1734  1205 Curtis Br Rd Ne      Swisher        Johnson

In [493]:
Store_Cleaned['Address Cleaned']=Store_Cleaned['Address Cleaned'].replace('Street$','St',regex = True)

In [505]:
#Store_Cleaned.to_csv('C:\\Users\\shiva\\Desktop\\DPA\\Master_Data_Stores_Cleaned.csv')

In [10]:
olddf=pandas.read_csv('C:\\Users\\shiva\\Desktop\\DPA\\Master_Data_Stores_Cleaned.csv')

In [3]:
# Get Store Number grouped by maximum date
liquor['Date'] = pandas.to_datetime(liquor['Date'])
liq = pandas.DataFrame(liquor.groupby(['Store Number'])['Date'].max()).reset_index()
#liq

In [5]:
min(liquor['Date'])


Timestamp('2012-01-03 00:00:00')

In [4]:
max(liquor['Date'])

Timestamp('2020-01-31 00:00:00')

In [42]:
type(liquor['Date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [159]:
# Get count of each repeating store number
temp = pandas.DataFrame(olddf['Store.Number'].value_counts()).reset_index()
temp = temp.rename(columns={"index": "Store Number", "Store.Number": "Count"})
temp = temp[temp['Count']>1]

In [160]:
temp['Store Number'].value_counts()

3582    1
2556    1
5088    1
4755    1
2656    1
4449    1
4254    1
4457    1
2669    1
5230    1
5876    1
4467    1
4419    1
5237    1
5241    1
4489    1
4222    1
4736    1
5249    1
4482    1
3461    1
5255    1
2696    1
5257    1
4169    1
5259    1
2238    1
3420    1
5200    1
3651    1
       ..
4090    1
2505    1
5828    1
5268    1
5287    1
4000    1
5271    1
4247    1
5273    1
4507    1
5276    1
3742    1
5280    1
5284    1
5285    1
5286    1
5288    1
5571    1
4777    1
4779    1
5298    1
5558    1
9911    1
5304    1
3772    1
4798    1
5005    1
5862    1
4319    1
4866    1
Name: Store Number, Length: 112, dtype: int64

In [161]:
temp = temp.merge(liq, on= 'Store Number', how = 'left')

In [162]:
temp

Store Number  Count       Date
0            4777      3 2020-01-22
1            5268      3 2020-01-31
2            4866      2 2020-01-29
3            5774      2 2019-12-24
4            5304      2 2018-10-30
5            5801      2 2020-01-31
6            5249      2 2018-02-26
7            4416      2 2018-03-19
8            5255      2 2020-01-27
9            5257      2 2020-01-31
10           3742      2 2020-01-28
11           5259      2 2020-01-30
12           5271      2 2020-01-28
13           5267      2 2020-01-31
14           5237      2 2020-01-31
15           5273      2 2020-01-29
16           5285      2 2019-11-30
17           5287      2 2020-01-29
18           5762      2 2020-01-29
19           4779      2 2020-01-03
20           4395      2 2020-01-21
21           5350      2 2020-01-24
22           5241      2 2020-01-27
23           5298      2 2020-01-27
24           3822      2 2020-01-31
25           9911      2 2018-07-25
26           3805      2 2020-01-27
27           4320      2 2020-01-31
28           5852      2 2020-01-20
29           4944      2 2020-01-10
..            ...    ...        ...
82           5695      2 2020-01-24
83           2505      2 2020-01-31
84           4507      2 2020-01-15
85           2515      2 2020-01-30
86           2523      2 2020-01-31
87           2656      2 2020-01-31
88           3403      2 2020-01-31
89           2689      2 2020-01-15
90           4736      2 2020-01-24
91           5869      2 2020-01-13
92           2578      2 2020-01-28
93           5005      2 2020-01-31
94           5230      2 2020-01-29
95           4254      2 2020-01-29
96           4067      2 2020-01-31
97           4116      2 2020-01-27
98           5097      2 2020-01-30
99           5876      2 2020-01-29
100          5200      2 2020-01-06
101          5140      2 2020-01-27
102          4000      2 2020-01-28
103          4222      2 2016-12-26
104          5091      2 2020-01-27
105          5214      2 2020-01-20
106          4247      2 2020-01-29
107          5862      2 2020-01-30
108          4090      2 2016-06-06
109          4132      2 2020-01-27
110          4169      2 2020-01-31
111          5124      2 2020-01-27

[112 rows x 3 columns]

In [73]:
# get details of repeating store numbers from orginal data 
m = df2[df2['Store Number'].isin(temp['Store Number'])]

In [74]:
len(m)

29011

In [75]:
#m = m[m['Date'].isin(temp['Date'])]
m = m[m['Date'].isin(temp['Date'])]

In [109]:
type(m)

pandas.core.frame.DataFrame

In [106]:
m = m.drop_duplicates()

In [89]:
olddf[olddf['Store.Number']==4777]

Unnamed: 0  Store.Number  Zip.Code                Store.Location  \
1934        1935          4777   51046.0   POINT (-95.684058 42.98282)   
2139        2140          4777   51046.0   POINT (-95.68472 42.982805)   
2187        2188          4777   51046.0  POINT (-95.684828 42.982332)   

         Address Cleaned City Cleaned County Cleaned  
1934     315 E Grand Ave     Paullina        O'brien  
2139     319 E Grand Ave     Paullina        O'brien  
2187  222 North Clark St     Paullina        O'brien

In [96]:
m[(m['Store Number']==5088) & (m['Date'] == '2018-03-27')]

Date  Store Number        Address     City Zip Code  \
3490489  2018-03-27          5088  107 IA HWY 60  Hospers    51238   
13098728 2018-03-27          5088  107 IA HWY 60  Hospers    51238   

         Store Location  County Number County  
3490489             NaN           84.0  SIOUX  
13098728            NaN           84.0  SIOUX

In [86]:
olddf[olddf['Store.Number']==5091]

Unnamed: 0  Store.Number  Zip.Code  \
1514        1514          5091   52671.0   
1873        1874          5091   52761.0   

                            Store.Location Address Cleaned City Cleaned  \
1514           POINT (-91.392568 40.92129)    416 Cedar St    Muscatine   
1873  POINT (-91.04614600000001 41.425095)    501 Cedar St    Muscatine   

     County Cleaned  
1514      Muscatine  
1873      Muscatine

In [163]:
#get latest store details for rpeating store numbers
temp = temp.merge(m,on = ('Store Number', 'Date'), how='left') 

In [164]:
temp

Store Number  Count       Date                       Address  \
0            4777      3 2020-01-22        222 North Clark Street   
1            5268      3 2020-01-31             188, Parkridge Rd   
2            4866      2 2020-01-29         429 Veterans Memorial   
3            5774      2 2019-12-24          1305 W Commercial St   
4            5304      2 2018-10-30                   210, Hwy 20   
5            5801      2 2020-01-31           4397 N Center Point   
6            5249      2 2018-02-26         1205/1207, Locust St.   
7            5249      2 2018-02-26         1205/1207, Locust St.   
8            4416      2 2018-03-19              501 McPherson St   
9            5255      2 2020-01-27           4100 University Ave   
10           5257      2 2020-01-31              405, Madison Ave   
11           3742      2 2020-01-28                1111 Holton Dr   
12           5259      2 2020-01-30                 924 Locust St   
13           5271      2 2020-01-28           135, Madison Street   
14           5267      2 2020-01-31             2320, 15th Street   
15           5237      2 2020-01-31                606, N 15th St   
16           5273      2 2020-01-29              414 Clark Street   
17           5285      2 2019-11-30               411 13th Street   
18           5285      2 2019-11-30               411 13th Street   
19           5287      2 2020-01-29             300 Central Ave W   
20           5762      2 2020-01-29                 8 Central Ave   
21           4779      2 2020-01-03           1305 E SOUTH STREET   
22           4395      2 2020-01-21           1111 Ia Highway 175   
23           5350      2 2020-01-24               680 Lindale Dr.   
24           5241      2 2020-01-27              1450, Loras Blvd   
25           5298      2 2020-01-27                  630, 6th Ave   
26           3822      2 2020-01-31          1205 Curtis Br Rd NE   
27           9911      2 2018-07-25  3100 SE Grimes Blvd. Ste 100   
28           3805      2 2020-01-27            1601 Washington St   
29           4320      2 2020-01-31               1315 Willis Ave   
..            ...    ...        ...                           ...   
86           5695      2 2020-01-24              315 Story Street   
87           2505      2 2020-01-31                  1111  8TH ST   
88           4507      2 2020-01-15                    411 W 18th   
89           2515      2 2020-01-30                2400 4th St SW   
90           2523      2 2020-01-31                    609 N 18th   
91           2656      2 2020-01-31                  300  10th St   
92           3403      2 2020-01-31              103 Walnut St. E   
93           2689      2 2020-01-15              8607 Douglas Ave   
94           4736      2 2020-01-24                  1225 7th Ave   
95           5869      2 2020-01-13              6941 Douglas Ave   
96           2578      2 2020-01-28                  901 Kelly St   
97           5005      2 2020-01-31                 410 W Main St   
98           5230      2 2020-01-29      3221, Center Point Rd NE   
99           4254      2 2020-01-29                 2008  12th St   
100          4067      2 2020-01-31                   268 8th Ave   
101          4116      2 2020-01-27                   223 Main St   
102          5097      2 2020-01-30               3717 1st Ave SE   
103          5876      2 2020-01-29                108 S Broadway   
104          5200      2 2020-01-06          3445, County Home Rd   
105          5140      2 2020-01-27            114 South  2nd  St   
106          4000      2 2020-01-28                     62 5th St   
107          4222      2 2016-12-26             3594 Lafayette St   
108          5091      2 2020-01-27                  416 Cedar St   
109          5214      2 2020-01-20             550 Wilson Ave SW   
110          4247      2 2020-01-29               512 River Ave N   
111          5862      2 2020-01-30              110 Airport Road   
112

In [125]:
temp['Store Number'].value_counts()

3582    1
4419    1
3651    1
4116    1
3420    1
4755    1
2656    1
4449    1
4254    1
4457    1
2669    1
5230    1
5876    1
5237    1
2556    1
5241    1
4489    1
4222    1
4736    1
2689    1
4482    1
3461    1
5255    1
2696    1
5257    1
4169    1
5205    1
5214    1
5200    1
3403    1
       ..
4599    1
4090    1
2505    1
5828    1
5267    1
5571    1
5268    1
5271    1
4247    1
5273    1
4507    1
5276    1
3742    1
4000    1
2238    1
5286    1
5287    1
5288    1
4777    1
4779    1
5298    1
5558    1
9911    1
5304    1
3772    1
4798    1
5005    1
5862    1
4319    1
4866    1
Name: Store Number, Length: 108, dtype: int64

In [170]:
temp

index  Store Number  Count       Date                       Address  \
0        0          4777      3 2020-01-22        222 North Clark Street   
1        1          5268      3 2020-01-31             188, Parkridge Rd   
2        2          4866      2 2020-01-29         429 Veterans Memorial   
3        3          5774      2 2019-12-24          1305 W Commercial St   
4        4          5304      2 2018-10-30                   210, Hwy 20   
5        5          5801      2 2020-01-31           4397 N Center Point   
6        6          5249      2 2018-02-26         1205/1207, Locust St.   
7        8          4416      2 2018-03-19              501 McPherson St   
8        9          5255      2 2020-01-27           4100 University Ave   
9       10          5257      2 2020-01-31              405, Madison Ave   
10      11          3742      2 2020-01-28                1111 Holton Dr   
11      12          5259      2 2020-01-30                 924 Locust St   
12      13          5271      2 2020-01-28           135, Madison Street   
13      14          5267      2 2020-01-31             2320, 15th Street   
14      15          5237      2 2020-01-31                606, N 15th St   
15      16          5273      2 2020-01-29              414 Clark Street   
16      17          5285      2 2019-11-30               411 13th Street   
17      19          5287      2 2020-01-29             300 Central Ave W   
18      20          5762      2 2020-01-29                 8 Central Ave   
19      21          4779      2 2020-01-03           1305 E SOUTH STREET   
20      22          4395      2 2020-01-21           1111 Ia Highway 175   
21      23          5350      2 2020-01-24               680 Lindale Dr.   
22      24          5241      2 2020-01-27              1450, Loras Blvd   
23      25          5298      2 2020-01-27                  630, 6th Ave   
24      26          3822      2 2020-01-31          1205 Curtis Br Rd NE   
25      27          9911      2 2018-07-25  3100 SE Grimes Blvd. Ste 100   
26      28          3805      2 2020-01-27            1601 Washington St   
27      29          4320      2 2020-01-31               1315 Willis Ave   
28      30          5852      2 2020-01-20              1515 11th Street   
29      31          4944      2 2020-01-10                   290, Hwy 28   
..     ...           ...    ...        ...                           ...   
82      86          5695      2 2020-01-24              315 Story Street   
83      87          2505      2 2020-01-31                  1111  8TH ST   
84      88          4507      2 2020-01-15                    411 W 18th   
85      89          2515      2 2020-01-30                2400 4th St SW   
86      90          2523      2 2020-01-31                    609 N 18th   
87      91          2656      2 2020-01-31                  300  10th St   
88      92          3403      2 2020-01-31              103 Walnut St. E   
89      93          2689      2 2020-01-15              8607 Douglas Ave   
90      94          4736      2 2020-01-24                  1225 7th Ave   
91      95          5869      2 2020-01-13              6941 Douglas Ave   
92      96          2578      2 2020-01-28                  901 Kelly St   
93      97          5005      2 2020-01-31                 410 W Main St   
94      98          5230      2 2020-01-29      3221, Center Point Rd NE   
95      99          4254      2 2020-01-29                 2008  12th St   
96     100          4067      2 2020-01-31                   268 8th Ave   
97     101          4116      2 2020-01-27                   223 Main St   
98     102          5097      2 2020-01-30               3717 1st Ave SE   
99     103          5876      2 2020-01-29                108 S Broadway   
100    104          5200      2 2020-01-06          3445, County Home Rd   
101    105          5140      2 2020-01-27            114 South  2nd  St   
102    106          4000      2 2020-01-28           

In [166]:
temp.drop_duplicates(subset ={"Store Number"},
                     keep = 'first', inplace = True)

In [169]:
temp = temp.reset_index()


In [203]:
temp.isnull().any()

Store Number      False
Count             False
Date              False
Address           False
City              False
Zip Code          False
Store Location    False
County             True
add                True
dtype: bool

In [140]:
olddf[olddf['Store.Number']==5268]

Unnamed: 0  Store.Number  Zip.Code                  Store.Location  \
562          562          5268   52206.0  POINT (-91.8627784 41.9924259)   
2049        2050          5268   52206.0  POINT (-95.7162018 37.2256055)   
2221        2222          5268   52206.0    POINT (-91.862705 41.992623)   

       Address Cleaned  City Cleaned County Cleaned  
562   188 Parkridge Rd        Atkins         Benton  
2049  188 Parkridge Rd  Independence     Montgomery  
2221  188 Parkridge Rd        Atkins         Benton

In [185]:
olddf = olddf.rename(columns={"Store.Number": "Store Number"})

In [190]:
# get unique store details
temp2 = temp.merge(olddf,on = ('Store Number', 'Store Location'), how='left') 

In [189]:
temp

Store Number  Count       Date                       Address  \
0            4777      3 2020-01-22        222 North Clark Street   
1            5268      3 2020-01-31             188, Parkridge Rd   
2            4866      2 2020-01-29         429 Veterans Memorial   
3            5774      2 2019-12-24          1305 W Commercial St   
4            5304      2 2018-10-30                   210, Hwy 20   
5            5801      2 2020-01-31           4397 N Center Point   
6            5249      2 2018-02-26         1205/1207, Locust St.   
7            4416      2 2018-03-19              501 McPherson St   
8            5255      2 2020-01-27           4100 University Ave   
9            5257      2 2020-01-31              405, Madison Ave   
10           3742      2 2020-01-28                1111 Holton Dr   
11           5259      2 2020-01-30                 924 Locust St   
12           5271      2 2020-01-28           135, Madison Street   
13           5267      2 2020-01-31             2320, 15th Street   
14           5237      2 2020-01-31                606, N 15th St   
15           5273      2 2020-01-29              414 Clark Street   
16           5285      2 2019-11-30               411 13th Street   
17           5287      2 2020-01-29             300 Central Ave W   
18           5762      2 2020-01-29                 8 Central Ave   
19           4779      2 2020-01-03           1305 E SOUTH STREET   
20           4395      2 2020-01-21           1111 Ia Highway 175   
21           5350      2 2020-01-24               680 Lindale Dr.   
22           5241      2 2020-01-27              1450, Loras Blvd   
23           5298      2 2020-01-27                  630, 6th Ave   
24           3822      2 2020-01-31          1205 Curtis Br Rd NE   
25           9911      2 2018-07-25  3100 SE Grimes Blvd. Ste 100   
26           3805      2 2020-01-27            1601 Washington St   
27           4320      2 2020-01-31               1315 Willis Ave   
28           5852      2 2020-01-20              1515 11th Street   
29           4944      2 2020-01-10                   290, Hwy 28   
..            ...    ...        ...                           ...   
82           5695      2 2020-01-24              315 Story Street   
83           2505      2 2020-01-31                  1111  8TH ST   
84           4507      2 2020-01-15                    411 W 18th   
85           2515      2 2020-01-30                2400 4th St SW   
86           2523      2 2020-01-31                    609 N 18th   
87           2656      2 2020-01-31                  300  10th St   
88           3403      2 2020-01-31              103 Walnut St. E   
89           2689      2 2020-01-15              8607 Douglas Ave   
90           4736      2 2020-01-24                  1225 7th Ave   
91           5869      2 2020-01-13              6941 Douglas Ave   
92           2578      2 2020-01-28                  901 Kelly St   
93           5005      2 2020-01-31                 410 W Main St   
94           5230      2 2020-01-29      3221, Center Point Rd NE   
95           4254      2 2020-01-29                 2008  12th St   
96           4067      2 2020-01-31                   268 8th Ave   
97           4116      2 2020-01-27                   223 Main St   
98           5097      2 2020-01-30               3717 1st Ave SE   
99           5876      2 2020-01-29                108 S Broadway   
100          5200      2 2020-01-06          3445, County Home Rd   
101          5140      2 2020-01-27            114 South  2nd  St   
102          4000      2 2020-01-28                     62 5th St   
103          4222      2 2016-12-26             3594 Lafayette St   
104          5091      2 2020-01-27                  416 Cedar St   
105          5214      2 2020-01-20             550 Wilson Ave SW   
106          4247      2 2020-01-29               512 River Ave N   
107          5862      2 2020-01-30              110 Airport Road   
108

In [192]:
temp2['Store Number'].value_counts()

5140    2
4944    2
5695    2
4416    2
4674    2
2514    2
5271    2
5276    2
3742    2
2604    2
5280    2
5304    2
4482    2
5298    2
3420    2
5088    2
5285    2
2656    2
5259    2
5267    2
4320    2
4067    2
2588    2
5237    2
4090    2
5255    2
3591    2
5241    2
3822    2
2543    2
       ..
5869    1
5618    1
4491    1
4853    1
4599    1
5571    1
5005    1
3461    1
4507    1
2696    1
5257    1
4169    1
2445    1
2556    1
5268    1
4000    1
4247    1
5273    1
4575    1
2238    1
5284    1
5286    1
5287    1
5288    1
4777    1
4779    1
5558    1
9911    1
3772    1
4866    1
Name: Store Number, Length: 112, dtype: int64

In [207]:
temp['County'] = temp['County'].str.title()

In [208]:
temp['County']=temp['County'].replace('Cerro Gord$','Cerro Gordo',regex = True)

In [210]:
temp['County']=temp['County'].replace('Obrien$',"O'brien",regex = True)  

In [213]:
temp['County']=temp['County'].replace('Pottawatta$',"Pottawattamie",regex = True)

In [216]:
temp['City'] = temp['City'].str.title()

In [236]:
temp['Address'] = temp['Address'].str.title()

In [235]:
temp['Zip Code'] = temp['Zip Code'].astype(float)

In [243]:
olddf = olddf.rename(columns={"County Cleaned": "County", "City Cleaned": "City", "Address Cleaned": "Address","Zip.Code": "Zip Code"})

In [288]:
#get unique store details
temp2 = temp.merge(olddf,on =('Store Number','Zip Code','Store Location','City','County','Address'),how ='left' )

In [303]:
temp2

Store Number  Count       Date                      Address  \
0            4777      3 2020-01-22           222 North Clark St   
1            5268      3 2020-01-31             188 Parkridge Rd   
2            4866      2 2020-01-29        429 Veterans Memorial   
3            5774      2 2019-12-24         1305 W Commercial St   
4            5304      2 2018-10-30                   210 Hwy 20   
5            5801      2 2020-01-31          4397 N Center Point   
6            5249      2 2018-02-26          1205/1207 Locust St   
7            4416      2 2018-03-19             501 Mcpherson St   
8            5255      2 2020-01-27          4100 University Ave   
9            5257      2 2020-01-31              405 Madison Ave   
10           3742      2 2020-01-28               1111 Holton Dr   
11           5259      2 2020-01-30                924 Locust St   
12           5271      2 2020-01-28               135 Madison St   
13           5267      2 2020-01-31                 2320 15Th St   
14           5237      2 2020-01-31                606 N 15Th St   
15           5273      2 2020-01-29                 414 Clark St   
16           5285      2 2019-11-30                  411 13Th St   
17           5287      2 2020-01-29            300 Central Ave W   
18           5762      2 2020-01-29                8 Central Ave   
19           4779      2 2020-01-03              1305 E South St   
20           4395      2 2020-01-21          1111 Ia Highway 175   
21           5350      2 2020-01-24               680 Lindale Dr   
22           5241      2 2020-01-27              1450 Loras Blvd   
23           5298      2 2020-01-27                  630 6Th Ave   
24           3822      2 2020-01-31         1205 Curtis Br Rd Ne   
25           9911      2 2018-07-25  3100 Se Grimes Blvd Ste 100   
26           3805      2 2020-01-27           1601 Washington St   
27           4320      2 2020-01-31              1315 Willis Ave   
28           5852      2 2020-01-20                 1515 11Th St   
29           4944      2 2020-01-10                   290 Hwy 28   
..            ...    ...        ...                          ...   
82           5695      2 2020-01-24                 315 Story St   
83           2505      2 2020-01-31                 1111  8Th St   
84           4507      2 2020-01-15                   411 W 18Th   
85           2515      2 2020-01-30               2400 4Th St Sw   
86           2523      2 2020-01-31                   609 N 18Th   
87           2656      2 2020-01-31                 300  10Th St   
88           3403      2 2020-01-31              103 Walnut St E   
89           2689      2 2020-01-15             8607 Douglas Ave   
90           4736      2 2020-01-24                 1225 7Th Ave   
91           5869      2 2020-01-13             6941 Douglas Ave   
92           2578      2 2020-01-28                 901 Kelly St   
93           5005      2 2020-01-31                410 W Main St   
94           5230      2 2020-01-29      3221 Center Point Rd Ne   
95           4254      2 2020-01-29                2008  12Th St   
96           4067      2 2020-01-31                  268 8Th Ave   
97           4116      2 2020-01-27                  223 Main St   
98           5097      2 2020-01-30              3717 1St Ave Se   
99           5876      2 2020-01-29               108 S Broadway   
100          5200      2 2020-01-06          3445 County Home Rd   
101          5140      2 2020-01-27           114 South  2Nd  St   
102          4000      2 2020-01-28                    62 5Th St   
103          4222      2 2016-12-26            3594 Lafayette St   
104          5091      2 2020-01-27                 416 Cedar St   
105          5214      2 2020-01-20            550 Wilson Ave Sw   
106          4247      2 2020-01-29              512 River Ave N   
107          5862      2 2020-01-30             110 Airport Road   
108          4090      2 2016-06-06               135 Madison

In [289]:
temp2['Store Number'].value_counts()

3582    1
2556    1
5088    1
4755    1
2656    1
4449    1
4254    1
4457    1
2669    1
5230    1
5876    1
4467    1
4419    1
5237    1
5241    1
4489    1
4222    1
4736    1
5249    1
4482    1
3461    1
5255    1
2696    1
5257    1
4169    1
5259    1
2238    1
3420    1
5200    1
3651    1
       ..
4090    1
2505    1
5828    1
5268    1
5287    1
4000    1
5271    1
4247    1
5273    1
4507    1
5276    1
3742    1
5280    1
5284    1
5285    1
5286    1
5288    1
5571    1
4777    1
4779    1
5298    1
5558    1
9911    1
5304    1
3772    1
4798    1
5005    1
5862    1
4319    1
4866    1
Name: Store Number, Length: 112, dtype: int64

In [284]:
temp['Address']=temp['Address'].replace(",","",regex=True)

In [285]:
temp['Address']=temp['Address'].replace("[.]","",regex=True)

In [286]:
temp['Address']=temp['Address'].str.title()

In [287]:
temp['Address']=temp['Address'].replace("Street","St",regex=True)

In [278]:
temp2 = temp2.rename(columns={"Address_x": "Address"})

In [279]:
temp2 = temp2.merge(olddf,on =('Store Number','Zip Code','Store Location','City','County','Address'),how ='left' )

In [283]:
len(temp2)

120

In [291]:
temp2

Store Number  Count       Date                      Address  \
0            4777      3 2020-01-22           222 North Clark St   
1            5268      3 2020-01-31             188 Parkridge Rd   
2            4866      2 2020-01-29        429 Veterans Memorial   
3            5774      2 2019-12-24         1305 W Commercial St   
4            5304      2 2018-10-30                   210 Hwy 20   
5            5801      2 2020-01-31          4397 N Center Point   
6            5249      2 2018-02-26          1205/1207 Locust St   
7            4416      2 2018-03-19             501 Mcpherson St   
8            5255      2 2020-01-27          4100 University Ave   
9            5257      2 2020-01-31              405 Madison Ave   
10           3742      2 2020-01-28               1111 Holton Dr   
11           5259      2 2020-01-30                924 Locust St   
12           5271      2 2020-01-28               135 Madison St   
13           5267      2 2020-01-31                 2320 15Th St   
14           5237      2 2020-01-31                606 N 15Th St   
15           5273      2 2020-01-29                 414 Clark St   
16           5285      2 2019-11-30                  411 13Th St   
17           5287      2 2020-01-29            300 Central Ave W   
18           5762      2 2020-01-29                8 Central Ave   
19           4779      2 2020-01-03              1305 E South St   
20           4395      2 2020-01-21          1111 Ia Highway 175   
21           5350      2 2020-01-24               680 Lindale Dr   
22           5241      2 2020-01-27              1450 Loras Blvd   
23           5298      2 2020-01-27                  630 6Th Ave   
24           3822      2 2020-01-31         1205 Curtis Br Rd Ne   
25           9911      2 2018-07-25  3100 Se Grimes Blvd Ste 100   
26           3805      2 2020-01-27           1601 Washington St   
27           4320      2 2020-01-31              1315 Willis Ave   
28           5852      2 2020-01-20                 1515 11Th St   
29           4944      2 2020-01-10                   290 Hwy 28   
..            ...    ...        ...                          ...   
82           5695      2 2020-01-24                 315 Story St   
83           2505      2 2020-01-31                 1111  8Th St   
84           4507      2 2020-01-15                   411 W 18Th   
85           2515      2 2020-01-30               2400 4Th St Sw   
86           2523      2 2020-01-31                   609 N 18Th   
87           2656      2 2020-01-31                 300  10Th St   
88           3403      2 2020-01-31              103 Walnut St E   
89           2689      2 2020-01-15             8607 Douglas Ave   
90           4736      2 2020-01-24                 1225 7Th Ave   
91           5869      2 2020-01-13             6941 Douglas Ave   
92           2578      2 2020-01-28                 901 Kelly St   
93           5005      2 2020-01-31                410 W Main St   
94           5230      2 2020-01-29      3221 Center Point Rd Ne   
95           4254      2 2020-01-29                2008  12Th St   
96           4067      2 2020-01-31                  268 8Th Ave   
97           4116      2 2020-01-27                  223 Main St   
98           5097      2 2020-01-30              3717 1St Ave Se   
99           5876      2 2020-01-29               108 S Broadway   
100          5200      2 2020-01-06          3445 County Home Rd   
101          5140      2 2020-01-27           114 South  2Nd  St   
102          4000      2 2020-01-28                    62 5Th St   
103          4222      2 2016-12-26            3594 Lafayette St   
104          5091      2 2020-01-27                 416 Cedar St   
105          5214      2 2020-01-20            550 Wilson Ave Sw   
106          4247      2 2020-01-29              512 River Ave N   
107          5862      2 2020-01-30             110 Airport Road   
108          4090      2 2016-06-06               135 Madison

In [295]:
 m2 = olddf[~olddf['Store Number'].isin(temp['Store Number'])]

In [300]:
m2=m2.reset_index()

In [301]:
m2 = m2.drop(['index'],axis=1)

In [302]:
m2.head()

Store Number  Zip Code                Store Location  \
0          2626   50311.0  POINT (-93.673222 41.600361)   
1          2501   50010.0  POINT (-93.619455 42.022848)   
2          2508   52405.0   POINT (-91.697941 41.97447)   
3          5314   51501.0  POINT (-95.847514 41.228712)   
4          2663   50322.0  POINT (-93.739105 41.629364)   

                     Address            City         County  
0        4100 University Ave      Des Moines           Polk  
1             640 Lincolnway            Ames          Story  
2     1843 Johnson Avenue Nw    Cedar Rapids           Linn  
3  3134 Manawa Center Dr # 9  Council Bluffs  Pottawattamie  
4               8701 Douglas       Urbandale           Polk

In [304]:
# merge non repeating and repeating unique stores
# we get a data frame of unique store numbers with all details
frames =[m2,temp2]

In [305]:
result=pandas.concat(frames)

C:\Users\shiva\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


In [310]:
result

Address               City         County  \
0            4100 University Ave         Des Moines           Polk   
1                 640 Lincolnway               Ames          Story   
2         1843 Johnson Avenue Nw       Cedar Rapids           Linn   
3      3134 Manawa Center Dr # 9     Council Bluffs  Pottawattamie   
4                   8701 Douglas          Urbandale           Polk   
5           1107 Se Army Post Rd         Des Moines           Polk   
6                     125 6th St               Ames          Story   
7                105 W Monroe St      Pleasantville         Marion   
8               4605 Fleur Drive         Des Moines           Polk   
9                 4607 N Pine St          Davenport          Scott   
10             115 South 29th St         Fort Dodge        Webster   
11           2508 Enterprise Ave        Spirit Lake      Dickinson   
12               103 Franklin St             Monona        Clayton   
13                 3500 Dodge St            Dubuque        Dubuque   
14               3221 Se 14th St         Des Moines           Polk   
15                 157 Locust St            Dubuque        Dubuque   
16   113 Se Delaware Ave Ste 101             Ankeny           Polk   
17              200 Se Laurel St             Waukee         Dallas   
18               626 Lincoln Way               Ames          Story   
19            3800 W Lincoln Way               Ames          Story   
20              1422 Flammang Dr           Waterloo     Black Hawk   
21           813 N Lincoln Ste 1          Knoxville         Marion   
22               110 Westgate Dr          Maquoketa        Jackson   
23                    823 2nd St       Webster City       Hamilton   
24                215 S Evans Rd          Evansdale     Black Hawk   
25               1661 32nd St Ne       Cedar Rapids           Linn   
26               6981 Ne 14th St             Ankeny           Polk   
27                  1460 2nd Ave         Des Moines           Polk   
28          4625 Se Delaware Ave             Ankeny           Polk   
29               1101 N Lake Ave         Storm Lake    Buena Vista   
..                           ...                ...            ...   
82                  315 Story St              Boone          Boone   
83                  1111  8Th St              Boone          Boone   
84                    411 W 18Th            Spencer           Clay   
85                2400 4Th St Sw         Mason City    Cerro Gordo   
86                    609 N 18Th        Centerville      Appanoose   
87                  300  10Th St            Corning          Adams   
88               103 Walnut St E  Columbus Junction         Louisa   
89              8607 Douglas Ave          Urbandale           Polk   
90                  1225 7Th Ave             Marion           Linn   
91              6941 Douglas Ave          Urbandale           Polk   
92                  901 Kelly St       Charles City          Floyd   
93                 410 W Main St            Laurens     Pocahontas   
94       3221 Center Point Rd Ne       Cedar Rapids           Linn   
95                 2008  12Th St         Emmetsburg      Palo Alto   
96                   268 8Th Ave            Wellman     Washington   
97                   223 Main St          Lake View            Sac   
98               3717 1St Ave Se       Cedar Rapids           Linn   
99                108 S Broadway          West Bend      Palo Alto   
100          3445 County Home Rd             Robins           Linn   
101           114 South  2Nd  St           Cherokee       Cherokee   
102                    62 5Th St           Woodbine       Harrison   
103            3594 Lafayette St          Evansdale     Black Hawk   
104                 416 Cedar St          Muscatine      Muscatine   
105            550 Wilson Ave Sw       Cedar Rapids           Linn   
106              512 River Ave N            Belmond         Wright   
107             110 Airport Road   

In [309]:
result = result.drop(['Count','Date','add'], axis=1)

In [311]:
result = result[['Store Number','Store Location','Address','Zip Code','City','County']]

In [312]:
result

Store Number                                Store Location  \
0            2626                  POINT (-93.673222 41.600361)   
1            2501                  POINT (-93.619455 42.022848)   
2            2508                   POINT (-91.697941 41.97447)   
3            5314                  POINT (-95.847514 41.228712)   
4            2663                  POINT (-93.739105 41.629364)   
5            2527                  POINT (-93.602372 41.526289)   
6            5187                  POINT (-93.611773 42.026938)   
7            4134                  POINT (-93.269702 41.386718)   
8            2561          POINT (-93.64494300000001 41.542748)   
9            4638                POINT (-90.6097959 41.5675513)   
10           2562          POINT (-94.15824700000002 42.504742)   
11           2233                  POINT (-95.126786 43.416433)   
12           3679                  POINT (-91.390767 43.055133)   
13           2524         POINT (-90.72213219999999 42.4907476)   
14           2633                  POINT (-93.596754 41.554101)   
15           3841                  POINT (-90.665439 42.495308)   
16           4165                  POINT (-93.581093 41.731416)   
17           4137                   POINT (-93.86786 41.614033)   
18           4129                  POINT (-93.618911 42.022854)   
19           2500                POINT (-93.6999877 42.0219973)   
20           2538                  POINT (-92.327917 42.459938)   
21           2566                POINT (-93.1094608 41.3250653)   
22           4051                  POINT (-90.680623 42.067391)   
23           2602                  POINT (-93.825486 42.469466)   
24           4153                  POINT (-92.287834 42.475631)   
25           4487                  POINT (-91.662119 42.010447)   
26           4767         POINT (-93.600659 41.687793000000006)   
27           2190                   POINT (-93.619787 41.60566)   
28           5144                     POINT (-93.581273 41.691)   
29           5067                  POINT (-95.200761 42.651369)   
..            ...                                           ...   
82           5695                  POINT (-93.879991 42.058784)   
83           2505                  POINT (-93.876107 42.063831)   
84           4507           POINT (-95.14471 43.14184000000001)   
85           2515                  POINT (-93.235588 43.148451)   
86           2523                  POINT (-92.867967 40.737577)   
87           2656                  POINT (-94.731809 40.991861)   
88           3403                  POINT (-91.359363 41.280107)   
89           2689                  POINT (-93.736835 41.629429)   
90           4736                  POINT (-91.596313 42.033295)   
91           5869                  POINT (-93.711496 41.629416)   
92           2578          POINT (-92.67556000000002 43.066993)   
93           5005                  POINT (-94.853219 42.846725)   
94           5230                   POINT (-91.663629 42.01133)   
95           4254                  POINT (-94.677307 43.109244)   
96           4067                  POINT (-91.837922 41.465008)   
97           4116          POINT (-95.051702 42.30568400000001)   
98           5097                POINT (-91.6330897 42.0162793)   
99           5876         POINT (-73.982421 40.305231000000006)   
100          5200  POINT (-91.69777959999999 42.09393710000001)   
101          5140                   POINT (-95.55132 42.749013)   
102          4000                  POINT (-95.702814 41.737038)   
103          4222         POINT (-92.29355090000001 42.4792103)   
104          5091                   POINT (-91.392568 40.92129)   
105          5214                  POINT (-91.676433 41.956073)   
106          4247                  POINT (-93.616788 42.850357)   
107          5862                  POINT (-93.610821 42.000991)   
108          4090          POINT (-92.53666400000002 42.951717)   
109          4132                  POINT (-90.257535

In [410]:
result.sort_values(by=['lat'])

Store Number                                Store Location  \
1993          9042  POINT (-95.21379809999999 29.66514789999999)   
2205          9936                 POINT (-104.845334 38.848017)   
99            5876         POINT (-73.982421 40.305231000000006)   
796           5046                  POINT (-91.391355 40.393735)   
2102          5826                  POINT (-91.382267 40.394752)   
848           2191                  POINT (-91.387797 40.400038)   
1089          4692                   POINT (-91.389502 40.40168)   
986           4993                  POINT (-91.390084 40.402244)   
853           3587          POINT (-91.39688800000002 40.408821)   
937           2555                   POINT (-91.403752 40.41538)   
1011          3811                  POINT (-91.407263 40.418589)   
2105          5827                  POINT (-91.410349 40.422672)   
2204          9937         POINT (-91.399797 40.473242000000006)   
1534          9037         POINT (-91.399797 40.473242000000006)   
1059          5062                  POINT (-91.415097 40.532149)   
901           5213                  POINT (-91.429681 40.552204)   
1160          4573                  POINT (-95.654604 40.605217)   
47            4419                  POINT (-93.896684 40.623454)   
1365          2674                  POINT (-93.924475 40.623647)   
190           4782                    POINT (-93.92909 40.62366)   
827           4793                  POINT (-91.377416 40.624074)   
2096          5783          POINT (-91.36180200000001 40.624094)   
470           3549          POINT (-91.373211 40.62422600000001)   
1154          4689                  POINT (-91.344306 40.626968)   
713           2584                  POINT (-91.343544 40.626988)   
2183          5892                  POINT (-91.337828 40.627164)   
2092          5784                  POINT (-91.319528 40.630103)   
1684          3908         POINT (-91.32836689999999 40.6301947)   
1961          5706                   POINT (-91.329797 40.63021)   
1856          4174           POINT (-91.32982400000002 40.63021)   
...            ...                                           ...   
716           4272                  POINT (-94.829963 43.402096)   
460           4774                  POINT (-94.822033 43.402229)   
1676          4187                  POINT (-95.759943 43.403935)   
920           4891                  POINT (-95.759943 43.403935)   
11            2233                  POINT (-95.126786 43.416433)   
54            3622                  POINT (-95.126535 43.416452)   
1415          5488                  POINT (-93.521318 43.419512)   
798           5069                  POINT (-93.532484 43.419608)   
1157          5334                  POINT (-93.535032 43.419668)   
1588          4276                  POINT (-93.535032 43.419668)   
833           5165                  POINT (-93.535032 43.419668)   
607           4239                   POINT (-95.106219 43.42157)   
2115          5812                  POINT (-95.109255 43.422638)   
542           4387                  POINT (-95.094324 43.422645)   
551           4582                   POINT (-95.126585 43.42282)   
508           2522         POINT (-95.14472450000001 43.4249041)   
860           4434                  POINT (-96.175502 43.430056)   
873           3705                POINT (-96.1716271 43.4318549)   
373           3664                  POINT (-93.218339 43.443739)   
1350          5388                   POINT (-93.35607 43.444415)   
1654          4839                  POINT (-93.220898 43.444481)   
1286          5383                  POINT (-93.220903 43.445493)   
938           4904                    POINT (-96.43415 43.45255)   
1005          4006                  POINT (-96.435452 43.453843)   
1014          5154                  POINT (-95.321385 43.454741)   
1648          4030                  POINT (-95.321385 43.454741)   
198           4529                  POINT (-93.917424 43.48410

In [395]:
result['lon'][0]

0   -93.6732
0   -95.6848
Name: lon, dtype: object

In [424]:
new[new['lat'].astype(float)==36.3634615]

Unnamed: 0  Store Number  Zip_Code              Address         City  \
293          294          5057     50317  4960 E Broadway Ave  Bentonville   
505          506          4410     50220          1219 1St St  Bentonville   
692          693          4382     50265         1293 8Th Ave  Bentonville   
784          785          4641     50315      5830 Se 14Th St  Bentonville   
1185        1186          4404     50021   1825 N Ankeny Blvd  Bentonville   
1193        1194          4385     50210      1453 Co Hwy G76  Bentonville   
1195        1196          4437     50010     4506 Lincoln Way  Bentonville   
1200        1201          4403     50311   7229 Universty Ave  Bentonville   
1220        1221          5107     50311  7229 University Ave  Bentonville   
1513        1515          5465     50010     4506 Lincoln Way  Bentonville   
1584        1595          5338     50313      5050 Nw 2Nd Ave  Bentonville   

            lon        lat                Store_Location  
293  -94.197322  36.363461  POINT (-94.197322 36.363461)  
505  -94.197322  36.363461  POINT (-94.197322 36.363461)  
692  -94.197322  36.363461  POINT (-94.197322 36.363461)  
784  -94.197322  36.363461  POINT (-94.197322 36.363461)  
1185 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1193 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1195 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1200 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1220 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1513 -94.197322  36.363461  POINT (-94.197322 36.363461)  
1584 -94.197322  36.363461  POINT (-94.197322 36.363461)

In [423]:
min(new['lat'])

36.3634615

In [9]:
liquor[liquor['Store Number']==9936]

Invoice/Item Number        Date  Store Number       Store Name  \
17703773     INV-09867400001  01/18/2018          9936  Dash Events LLC   
17717824     INV-09867400002  01/18/2018          9936  Dash Events LLC   

                         Address              City Zip Code  \
17703773  1685 W Uintah St. #101  Colorado Springs    80904   
17717824  1685 W Uintah St. #101  Colorado Springs    80904   

                         Store Location  County Number   County  ...  \
17703773  POINT (-104.845334 38.848017)            NaN  EL PASO  ...   
17717824  POINT (-104.845334 38.848017)            NaN  EL PASO  ...   

          Item Number              Item Description  Pack Bottle Volume (ml)  \
17703773        78592  Adelaides Caramel Mocha Mojo    12                750   
17717824        71412     Adelaides Coconut Liqueur    12                750   

         State Bottle Cost State Bottle Retail  Bottles Sold  Sale (Dollars)  \
17703773             10.38               15.57             6           15.57   
17717824             10.38               15.57             6           15.57   

          Volume Sold (Liters)  Volume Sold (Gallons)  
17703773                   4.5                   1.18  
17717824                   4.5                   1.18  

[2 rows x 24 columns]

In [ ]:
result.to_csv('C:\\Users\\shiva\\Desktop\\DPA\\Master_Data_Stores_Cleaned_final.csv')